### ISSUE TITLE
Huge description.csv file size?

### ISSUE THREAD

**Issue by kvbulusu** [leanderme/sytora#11]
Hi, a quick qn. When we run generatelabels.py , I see the descriptions.csv is almost 350GB? Not sure how to reduce the file size? Is it dependant on the  umls config file? Can you share yours?

**Comment by leanderme** [comment]
Hi, sorry for your troubles. This project was written rather fast and the code base is a mess. The reason is indeed most likely your umls installation. I'm suspecting that you've included to many languages and would recommend to select only those you're interested in (f.i., like in this project only ENG and GER). I don't have access to my workstation atm, but the installation process and configuration settings are well documented.

**Comment by leanderme** [comment]
Closing for now, let me know if the issue persists.

**Comment by Duxtie** [comment]
Also, What Semantic Types is required, as the descriptions.csv is climbing 1TB.
Thank you.
